version: "24.0.7"
services:
  java_app:
    container_name: java_app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/miprimeraapi
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=123456789
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: miprimeraapi
      MYSQL_ROOT_PASSWORD: 123456789
